### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by robvanuden** [costastf/mapscookiegettercli#2]
Thanks for making this library! I wanted to test the new authentication method from the initial-usability branch, but it doesn't work totally yet. FYI: I'm currently on Windows and have few experience with python.
Everything goes well until I execute "_activate":

```
$ _activate                                                                      
Could not find virtual environment to activate
```

Instead, I ran "pipenv shell" and ran "maps-cookie-getter". Then I got this error:

`2019-03-07 12:57:06 HOMESERVER cookiegetter.CookieGetter[5700] INFO Identified  OS as windows                                                                    2019-03-07 12:57:06 HOMESERVER cookiegetter.CookieGetter[5700] INFO Identified  default browser as firefox                                                       2019-03-07 12:57:06 HOMESERVER cookiegetter.CookieGetter[5700] INFO Set seleniu m drivers path as "c:\code\mapscookiegettercli\.venv\lib\site-packages\mapscooki egettercli\library\..\drivers"                                                   2019-03-07 12:57:06 HOMESERVER cookiegetter.CookieGetter[5700] INFO Bootstrappi ng selenium by downloading appropriate driver                                    INFO geckodriver is up to date                                                   2019-03-07 12:57:08 HOMESERVER webdriver_manager[5700] INFO geckodriver is up t o date                                                                           INFO geckodriver version found: 0.24.0                                           2019-03-07 12:57:08 HOMESERVER webdriver_manager[5700] INFO geckodriver version  found: 0.24.0                                                                   Traceback (most recent call last):                                                 File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\Lib\run py.py", line 193, in _run_module_as_main                                             "__main__", mod_spec)                                                          File "C:\Users\xx\AppData\Local\Programs\Python\Python37-32\Lib\run py.py", line 85, in _run_code                                                        exec(code, run_globals)                                                        File "C:\code\mapscookiegettercli\.venv\Scripts\maps-cookie-getter.exe\__main_ _.py", line 9, in                                                          File "c:\code\mapscookiegettercli\.venv\lib\site-packages\mapscookiegettercli\ mapscookiegettercli.py", line 92, in main                                            getter.run()                                                                   File "c:\code\mapscookiegettercli\.venv\lib\site-packages\mapscookiegettercli\ library\cookiegetter.py", line 166, in run                                           driver_name = versions['chromedriver'][0][1]                                 KeyError: 'chromedriver'`

Can you help me?

**Comment by robvanuden** [comment]
And of course, if you can not help me, I hope creating this issue helps you creating the library :-)

**Comment by costastf** [comment]
Hi @robvanuden , thanks for reporting this but as I mentioned on the message this is a proof of concept and currently only works with Mac os and Chrome. (Linux with chrome should work also) I do not want to go down any rabbit holes currently and just built up usability slowly so I do not want to start chasing around for Windows. 
If you can please setup an ubuntu box with chrome as default browser and try that out, i hope that would work for you and you can move forward. 
I appreciate the report and it will come handy but as you can imagine the matrix is quite big with Mac, Linux, Windows, and chrome, firefox, opera, edge and IE, which is what I hope to support in the future, that is why windows will go last since it has those two corner cases and mac and linux are more or less compatible in that sense.
The reason why it blows up for you is because I am using https://pypi.org/project/py-webdriver-manager/ for bootstrapping of the browsers and that has a very narrow compatiblitiy list. 
Most of the work needs to be put into a webdriver manager since the ones out there do not do what I would want them, except a java one https://github.com/bonigarcia/webdrivermanager but having a java cli dependency feels kind of wrong.
Anyway, please try a linux installation with chrome and I hope you want to test things out and help with issues when I start working on the windows part.

**Comment by robvanuden** [comment]
OK, my intention was not getting it working for me. I just wasn't sure if it had something to do with my environment or the library :) Thanks for your reponse, I will try that!

**Comment by robvanuden** [comment]
After checking the link you sent, I tweaked some code, put the chromedriver manually in the driver directory and got it working :-) If you need information, please ask.

**Comment by costastf** [comment]
That's great! As I told you that component is in temporarily just for the poc so I am not going to invest much on it, but thanks for you offer :)

**Comment by costastf** [comment]
Maybe it wouldn't hurt though for someone coming into this issue if they want to manually get things going for them, so if you don't mind please extend the thread with what you did.
