### ISSUE TITLE
Support for WSL

### ISSUE THREAD

**Issue by macf0x** [costastf/mapscookiegettercli#8]
Unable to run this script under WSL (win 10)

`2019-08-05 02:38:34 WSLWIN10 cookiegetter.CookieGetter[33] INFO Identified OS as linux
Could not execute xdg-settings, probably unsupported version of linux.
Traceback (most recent call last):
  File "/home/user/.local/bin/maps-cookie-getter", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/mapscookiegettercli/mapscookiegettercli.py", line 91, in main
    getter = CookieGetter()
  File "/home/user/.local/lib/python3.6/site-packages/mapscookiegettercli/library/cookiegetter.py", line 81, in __init__
    self.default_browser = self._identify_default_browser(self.os)
  File "/home/user/.local/lib/python3.6/site-packages/mapscookiegettercli/library/cookiegetter.py", line 101, in _identify_default_browser
    raise UnsupportedDefaultBrowser
mapscookiegettercli.mapscookiegettercliexceptions.UnsupportedDefaultBrowser`

Attempted to modify the code to launch 
`/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe` 
which works from bash, but not in the script.

**Comment by costastf** [comment]
I am very sorry, but wsl is completely out of my scope. I do not use Windows at all and wsl creates a huge amount of complexity. Please install python on your Windows installation through the app store and install the script in your native python. It has been tested working in native Windows with firefox, Chrome and edge.

**Comment by macf0x** [comment]
Thanks for the reply. I understand. I'm coming from a Hass.io env and really looking for a more accessible way to get this cookie file for Hass users (including) myself.

As I'm sure you're aware the library i now included in the base app, but there is no easy way to generate that cookie file under hass.io (docker based).

A Win32 compiled version of your script would be really great. Install Python and related dependencies under Windows is a big hurdle, just to get a cookie file. WSL takes are of POSIX compatibility so you can get a native linux experience.

If I understood the requirements and logic of the Python script I could code in PowerShell, which would make it much more accessible.

**Comment by costastf** [comment]
Installing python in latest Windows is as easy as going to the software center, or however it's called in Windows and clicking install. Then you pip install the tool and run it. There is no need to install any dependencies as they are all managed by pip. Essentially this is as easy as downloading any executable and running it, with the added benefit of being more secure. I would not trust to execute any binary I got from the internet on a Windows box.Please try this out.

**Comment by costastf** [comment]
This is how you install python for windows. https://www.microsoft.com/en-us/p/python-37/9nj46sx7x90p?activetab=pivot:overviewtab

**Comment by macf0x** [comment]
I conceed it's probably not that hard, but its a lot harder than other location tracking setups in hass.

Installing a whole framework just to run the script is a challenge most would balk at TBH. Many would be happy to download a exe from a trusted repo such as yours.

The challenge of getting that binary cookie file into hass is not your issue, but could be made easier. With WSL i can transfer it with minimal work. If the library accepted it in base64 then it could be transfered through the text editor within hass.

What you've created is awesome and I'm trying to make it more accessible as many are getting tripped up by the cookie setup and moving to alternatives.

**Comment by costastf** [comment]
I understand your point, but essentially that is exactly what I am saying
too. When you pip install the tool you get a windows exe out of the box
that you can execute. The only prerequisite is having python installed.
Having a binary would get around that step and if you think that that would
be so much more beneficial for people I can try to make one. What I am
worried about is that that will just make the matrix of support much
bigger. Consider that this has been built to work for linux, mac and
windows with standard installations and support firefox, chrome and edge
(limited testing). People are trying to run this on Raspberry Pi which
exposes firefox differently, you wanted to have this in wsl, i am not sure
what problems will arise coming from a binary and that makes me a bit
worried, since my time is very limited and I already have too much stuff on
my plate. Of course I would more than welcome any PR that implements extra
functionality but I am worried that expanding the matrix will create a huge
overhead in managing a project that is essentially meant to be used once to
make a cookie file.

**Comment by macf0x** [comment]
I'll see if I can convert it to PowerShell. Just need to refresh my python skills.

Is there any reason the cookie file is binary rather than say base64 encoded?

**Comment by costastf** [comment]
No, not really, i just went with pickle because that is the standard way to
"snapshot" objects in python with standard library. I would suggest to go
with pyinstaller and make a portable binary instead of rewritting it in
powershell. If you are willing to beta test stuff I could give it a go at
bundling it. I am fine with that, I just do not have time to troubleshoot
windows issues, so if you are up for it we could try to fix this this way.

**Comment by macf0x** [comment]
For sure. Happy to beta test the exe.
